### ISSUE TITLE
Investigate scale-down issues for read replica autoscaling

### ISSUE THREAD

**Issue by vladvataws** [aws-samples/amazon-aurora-labs-for-mysql#3]
application auto-scaling does not always remove the additional read replica after the load generator is stopped.

**Comment by ovi-hutu-aws** [comment]
Hi Vlad, 
I see that the Autoscaling Alarm TargetTracking-cluster:auroralab-mysql-cluster-AlarmLow-xxxx for Low value (scale-in) in CloudWatch is set to my desired scale-in CPU percent, but it has 15 data points configured. This means the scale-in activity will need at least 15 consecutive minutes before triggering the alarm. The Autoscaling Alarm for High Value (scale-out) has only 3 data points configured. This is maybe why the scale-in takes longer.

**Comment by vladvataws** [comment]
Currently, target tracking auto-scaling policies do not allow the customization of the number of data points collected for the underlying High/Low Alarms. Changing this would require externally modifying service managed resources, which might introduce other issues. Observing/testing scale down is an optional lab objective and not required to complete the lab.
