### ISSUE TITLE
Error when running das_reader.py

### ISSUE THREAD

**Issue by PreciousPL** [aws-samples/amazon-aurora-labs-for-mysql#34]
Hi, I ran into below error when working on "Step 4. Read activity from the stream" of "Set up Database Activity Streams (DAS)". Looks like the script assumes an older version of AWS Encryption SDK. Thanks!

buntu@ip-172-31-0-243:~$ python3 das_reader_new.py -i cluster-M7KHZGHKIMDTO2CJSRRMUJDFVA -s aws-rds-das-cluster-M7KHZGHKIMDTO2CJSRRMUJDFVA
Press Ctrl+C to quit this test...
Filtering is enabled, only user events are displayed, service events are skipped. Disable with parameter '-f0'.
Traceback (most recent call last):
  File "das_reader_new.py", line 153, in <module>
    plaintext = decrypt_decompress(payload_decoded, data_key_decrypt_result['Plaintext']).decode('utf8')
  File "das_reader_new.py", line 104, in decrypt_decompress
    decrypted = decrypt_payload(payload, key)
  File "das_reader_new.py", line 97, in decrypt_payload
    decrypted_plaintext, header = aws_encryption_sdk.decrypt(
AttributeError: module 'aws_encryption_sdk' has no attribute 'decrypt'

**Comment by vladvataws** [comment]
Fixed with release v1.3.1
