### ISSUE TITLE
Database Activity Streams lab in website has incorrect references to pgSQL + das-script.py

### ISSUE THREAD

**Issue by alvinteh** [aws-samples/amazon-aurora-labs-for-mysql#54]
I was trying to run the labs for database activity streams based on instructions from the Aurora Labs for [MySQL website](https://awsauroralabsmy.com/win/apg-das/), and noticed a few issues in the DAS section.

There are a number of references to PostgreSQL that should be references to MySQL instead. In addition, step 4 references '/home/ec2-user/das-script.py', but the provisioned script is actually `/home/ubuntu/das_reader.py`. Inspection of that script also shows that the way to configure the cluster ID and stream ID have changed from values we need to specify in the source code to command line parameters.

The [associated MD file](https://github.com/aws-samples/amazon-aurora-labs-for-mysql/blob/9b63dd900c6b943cdc09f620472356746bae3b6a/docs/provisioned/das/index.md) in this repo does not have the aforementioned issues however. This leads me to think that the version of the labs deployed in the website is not up to date.

**Comment by vladvataws** [comment]
HI Alvin,

I think you are looking at the wrong Database Activity Streams (DAS) lab. The correct DAS lab for MySQL is under Provisioned > Set up Database Activity Streams at ([https://awsauroralabsmy.com/provisioned/das/](https://awsauroralabsmy.com/provisioned/das/)). The lab you referenced is part of a dedicated workshop called Win the Data, that includes labs for both Aurora MySQL and PostgreSQL. That workshop is deprecated, and will be removed from the site with our next major release.

**Comment by vladvataws** [comment]
Win the Data labs have been removed in 1.5.0. This is no longer an issue.
