### ISSUE TITLE
Auto-generated passwords break python commands

### ISSUE THREAD

**Issue by rottama** [aws-samples/amazon-aurora-labs-for-mysql#57]
If you are unfortunate enough that the auto generated password starts with an equal sign (=), the workshop's python commands do not work: (from R2, Connect, Load Data and Auto Scale)

`python3 reader_loadtest.py -e[readerEndpoint] -u$DBUSER -p"$DBPASS" -dmylab`

returns

`(1045, "Access denied for user 'masteruser'@'172.31.0.7' (using password: YES)")`

while the same mysql command works:
`mysql -hauroralab-mysql-node-2.ciwmnxgn1aeo.eu-central-1.rds.amazonaws.com -u$DBUSER -p"$DBPASS" mylab`
`Welcome to the MySQL monitor.  [...]
mysql>`

because the command line parser used in the python script glosses over the `=` at the start of parameter `-p`.

You have to either generate passwords without the equal sign or put a space in between: `-p "$DBPASS"`

**Comment by vladvataws** [comment]
Thank you for reporting this! A fix will be deployed at the end of 9/2021, part of our next release. We will be excluding the "=" (equal sign) from the random password generator. We have encountered issues in the past when there was a space between the parameter (eg `-p`) and the value.

**Comment by vladvataws** [comment]
Fixed in 1.5.0
